language: python

python:
  - "3.6"

cache: pip

install:
  - pip install -r requirements.txt

before_script:
  - pip install coverage
  - pip install coveralls
  - pip install codecov

script:
  - python test_gradients.py
  - coverage run test_gradients.py

after_success:
  - codecov
